### ISSUE TITLE
CMake configure error on Windows 10

### ISSUE THREAD

**Issue by liaoclarke** [OSVR/libfunctionality#18]
Following is the configure error reported by cmake. It sounds a file named libfunctionalityTargets.cmake can't be found in the root directory of libfunctionality.

CMake Error at D:/GitHub/osvr/libfunctionality/libfunctionalityConfig.cmake:1 (include):
  include could not find load file:

    D:/GitHub/osvr/libfunctionality/libfunctionalityTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:189 (find_package)

**Comment by beeryt** [comment]
I am having this problem as well. Creating a blank libfunctionalityTargets.cmake file allows configure to complete, but then CMake throws a bunch of warnings and errors during generate.

**Comment by beeryt** [comment]
Well I managed to find a sort of fix. This is for running CMake on OSVR-Core. I have no issues running CMake on libfunctionality on its own.

1. git clone https://github.com/OSVR/libfunctionality.git
2. CMake the source directory
3. grab libfunctionalityTargets.cmake from the bin path
4. Add libfunctionalityTargets.cmake to the original source folder

![cmake config_small](https://cloud.githubusercontent.com/assets/14947602/15725589/7531e922-2801-11e6-84fc-4e8e3cb34f59.png)

5. Do like the picture
6. Configure
7. Generate

**Comment by godbyk** [comment]
When building OSVR-Core, I usually set `CMAKE_PREFIX_PATH` to point to the location where libfunctionality is installed. Then CMake will automatically find the libfunctionality cmake files and everything else it needs to make use of libfunctionality.

**Comment by beeryt** [comment]
Ok I was going around in circles for a while and forgot to try that. It works. It is what I did for jsoncpp. I'm still having an issue with build errors though. My current issue is closer to https://github.com/OSVR/OSVR-Core/issues/437.

**Comment by godbyk** [comment]
Per https://github.com/OSVR/OSVR-Core/issues/437#issuecomment-236320079, this issue has been solved.
