### ISSUE TITLE
Set up travis.ci builds

### ISSUE THREAD

**Issue by rpavlik** [OSVR/libfunctionality#7]
Would be good to try a Mac OS X build, while we're at it, but starting with the linux build would be good.

**Comment by godbyk** [comment]
See https://github.com/OSVR/libfunctionality/pull/20. See also https://github.com/OSVR/libfunctionality/pull/21 for Appveyor support for building on Windows.

**Comment by rpavlik** [comment]
Thanks for doing this long ago. I've updated them so they pass again.
