### ISSUE TITLE
CMakeLists.txt should have a larger minimum version number

### ISSUE THREAD

**Issue by russell-taylor** [OSVR/libfunctionality#9]
The export(EXPORT ... command is not understood on the standard version of Cmake installed on Ubuntu 14.04, which is version 2.8.12.2, even though it claims to work on 2.8.12.  It does work under version 3.2.1, which must be installed by hand using a script from CMake.org.

Probably should either bump the required version or change the file to conform to the old standard again.

**Comment by olsoneric** [comment]
I ran into this problem too.  I checked which version it works for and updated the requirement in this PR: https://github.com/OSVR/libfunctionality/pull/10
Making cmakelists backwards-compatible instead would also work - I don't know enough cmake to make that change.
